Added missing include to satisfy certain versions of clang
Some compilers, such as PS4's clang, were giving errors such as:
C:\dev\protobuf\src\google/protobuf/parse_context.h(227,5): error : no type named 'uintptr_t' in namespace 'std'; did you mean simply 'uintptr_t'?
Adding the necessary include for integer types fixes these.